// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoTCH5aw1GQwrT4mw5MgP-T59d_PYwvgw',
    appId: '1:92132858507:web:f329bc9aa4659e8668128e',
    messagingSenderId: '92132858507',
    projectId: 'sewamotorlistrik-9082b',
    authDomain: 'sewamotorlistrik-9082b.firebaseapp.com',
    storageBucket: 'sewamotorlistrik-9082b.firebasestorage.app',
    measurementId: 'G-BP9K5FSMZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBSsMbITA02u4zYC2GO5eBuqCDksO19Hs',
    appId: '1:92132858507:android:2e132709391c0b2068128e',
    messagingSenderId: '92132858507',
    projectId: 'sewamotorlistrik-9082b',
    storageBucket: 'sewamotorlistrik-9082b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoTCH5aw1GQwrT4mw5MgP-T59d_PYwvgw',
    appId: '1:92132858507:web:4a0a6f63aa76c3ad68128e',
    messagingSenderId: '92132858507',
    projectId: 'sewamotorlistrik-9082b',
    authDomain: 'sewamotorlistrik-9082b.firebaseapp.com',
    storageBucket: 'sewamotorlistrik-9082b.firebasestorage.app',
    measurementId: 'G-G1JC6YFMF8',
  );
}
